/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package booking;

import home_page.Home;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Booking extends javax.swing.JFrame {
byte[] image = null;
String carid =null;
String custid = null;
 String carmodel = null;
  String carmake= null;
  String phone = null;
    Connection con = null;
    PreparedStatement pst =null;
    PreparedStatement pst2 =null;
      PreparedStatement pst1 =null;
      ResultSet rs1;
      PreparedStatement pst3 =null;
    ResultSet rs3;
      ResultSet rs;
    /**
     * Creates new form Booking
     */
    public Booking() {
        initComponents();
       
        loadcarid();
//         cmbcarid.setEnabled(false);
         txtcusid.setEnabled(false);
         txtcusname.setEnabled(false);
         txtphone.setEnabled(false);
         txtrentalfee.setEnabled(false);
                
    
        
    }

    public void loadcarid()
    {
        try {
            con =DriverManager.getConnection("jdbc:mysql://localhost:3306/carhire","root","34852684");
            pst =con.prepareStatement("SELECT * FROM `vehicle`");
            rs = pst.executeQuery();
            cmbcarid.removeAllItems();
            
         while(rs.next()) 
         {
         cmbcarid.addItem(rs.getString(1));
         
         }  
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }  
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        txtcusid = new javax.swing.JTextField();
        txtcusname = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtphone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtrentalfee = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cmbcarid = new javax.swing.JComboBox<>();
        jlbimg = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        txtduedate = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        txtpickdate = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtrentalid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtcarmake = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        txtcarmodell = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(java.awt.Color.white);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Rental Fee :");
        jLabel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Customer id :");
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Custoner name:");
        jLabel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 88, 28));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Back");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 70, -1));

        jButton5.setBackground(new java.awt.Color(0, 88, 28));
        jButton5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Rent");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 70, 30));

        jButton6.setBackground(new java.awt.Color(0, 88, 28));
        jButton6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("Cancle");
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, 80, -1));

        txtcusid.setBackground(java.awt.Color.white);
        txtcusid.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtcusid.setForeground(new java.awt.Color(0, 0, 0));
        txtcusid.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtcusid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcusidKeyPressed(evt);
            }
        });
        jPanel6.add(txtcusid, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 180, 20));

        txtcusname.setBackground(java.awt.Color.white);
        txtcusname.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtcusname.setForeground(new java.awt.Color(0, 0, 0));
        txtcusname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(txtcusname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 180, 20));

        jPanel7.setBackground(new java.awt.Color(0, 255, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 180, 1));

        jPanel8.setBackground(new java.awt.Color(0, 255, 51));
        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 180, 1));

        jPanel9.setBackground(new java.awt.Color(0, 255, 51));
        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 180, 1));

        jPanel4.setBackground(new java.awt.Color(0, 255, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 180, 1));

        txtphone.setBackground(java.awt.Color.white);
        txtphone.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtphone.setForeground(new java.awt.Color(0, 0, 0));
        txtphone.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 180, 20));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Phone no :");
        jLabel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        txtrentalfee.setBackground(java.awt.Color.white);
        txtrentalfee.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtrentalfee.setForeground(new java.awt.Color(0, 0, 0));
        txtrentalfee.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(txtrentalfee, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 180, 20));

        jPanel10.setBackground(new java.awt.Color(0, 255, 51));
        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 180, 1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Car id :");
        jLabel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        cmbcarid.setBackground(new java.awt.Color(0, 153, 51));
        cmbcarid.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmbcarid.setForeground(new java.awt.Color(0, 0, 0));
        cmbcarid.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbcarid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbcaridItemStateChanged(evt);
            }
        });
        cmbcarid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcaridActionPerformed(evt);
            }
        });
        cmbcarid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbcaridKeyPressed(evt);
            }
        });
        jPanel6.add(cmbcarid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 180, -1));

        jlbimg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 102), new java.awt.Color(102, 255, 102), new java.awt.Color(102, 255, 102), new java.awt.Color(102, 255, 153)));
        jPanel6.add(jlbimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 300, 200));

        jButton7.setBackground(new java.awt.Color(0, 88, 28));
        jButton7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("print");
        jButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, 70, -1));

        txtduedate.setBackground(java.awt.Color.white);
        txtduedate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtduedate.setForeground(new java.awt.Color(0, 0, 0));
        txtduedate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(txtduedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 180, 20));

        jPanel11.setBackground(new java.awt.Color(0, 255, 51));
        jPanel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 180, 1));

        jTextArea1.setBackground(java.awt.Color.white);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 0), new java.awt.Color(0, 204, 0), new java.awt.Color(51, 255, 0), new java.awt.Color(153, 204, 0)));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 320, 380));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Due date :");
        jLabel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jPanel12.setBackground(new java.awt.Color(0, 255, 51));
        jPanel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 180, 1));

        txtpickdate.setBackground(java.awt.Color.white);
        txtpickdate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtpickdate.setForeground(new java.awt.Color(0, 0, 0));
        txtpickdate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(txtpickdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 180, 20));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Pick date :");
        jLabel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Image");
        jLabel14.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Available");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 60, 20));

        jPanel14.setBackground(new java.awt.Color(0, 255, 51));
        jPanel14.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 180, 1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Rental id  :");
        jLabel15.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        txtrentalid.setBackground(java.awt.Color.white);
        txtrentalid.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtrentalid.setForeground(new java.awt.Color(0, 0, 0));
        txtrentalid.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(txtrentalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 180, 20));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 70, 30));

        jPanel13.setBackground(new java.awt.Color(0, 255, 51));
        jPanel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 180, 1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Car Make :");
        jLabel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtcarmake.setBackground(java.awt.Color.white);
        txtcarmake.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtcarmake.setForeground(new java.awt.Color(0, 0, 0));
        txtcarmake.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtcarmake.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcarmakeKeyPressed(evt);
            }
        });
        jPanel6.add(txtcarmake, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 180, 20));

        jPanel15.setBackground(new java.awt.Color(0, 255, 51));
        jPanel15.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 180, 1));

        txtcarmodell.setBackground(java.awt.Color.white);
        txtcarmodell.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtcarmodell.setForeground(new java.awt.Color(0, 0, 0));
        txtcarmodell.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtcarmodell.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcarmodellKeyPressed(evt);
            }
        });
        jPanel6.add(txtcarmodell, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 180, 20));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Car Model:");
        jLabel16.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Please  Enter you Customer Id Below To Rent Car");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 15, 360, 20));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 790, 640));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 800, 640));

        jPanel1.setBackground(new java.awt.Color(51, 27, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Booking");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 12, 132, 28));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcarmakeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcarmakeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcarmakeKeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed






        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cmbcaridKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbcaridKeyPressed

        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {

            String carid =cmbcarid.getSelectedItem().toString();
            try {

                con =DriverManager.getConnection("jdbc:mysql://localhost:3306/carhire","root","34852684");
                pst3 =con.prepareStatement("SELECT * FROM `vehicle` WHERE Car_id=?");
                pst3.setString(1, carid);

                rs1 = pst3.executeQuery();

                if(rs1.next()==false)
                {
                    JOptionPane.showMessageDialog(this,"car not available");
                }
                else
                {

                    String aval=rs1.getString("Status");
                    jLabel3.setText(aval.trim());
                    
                     String carmodel=rs1.getString("Model");
                    txtcarmodell.setText(carmodel.trim());
                    
                     String carmake=rs1.getString("make");
                    txtcarmake.setText(carmake.trim());

                    byte[] image =rs1.getBytes("Image");
                    jlbimg.setIcon(new ImageIcon(image));

                    if(aval.equals("Yes"))
                    {

                        txtcusid.setEnabled(true);
                        txtcusname.setEnabled(true);
                        txtphone.setEnabled(true);
                        txtrentalfee.setEnabled(true);

                    }

                    else
                    {
                        JOptionPane.showMessageDialog(null,"CAR NOT AVAILABLE CHOOSE OTHERS");
                        //           cmbcarid.setSelectedItem(-1);
                        txtcusid.setEnabled(false);
                        txtcusname.setEnabled(false);
                        txtphone.setEnabled(false);
                        txtrentalfee.setEnabled(false);
                    }

                }

                // TODO add your handling code here:
            } catch (SQLException ex) {
                Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
            }}// TODO add your handling code here:
    }//GEN-LAST:event_cmbcaridKeyPressed

    private void cmbcaridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcaridActionPerformed

      
    }//GEN-LAST:event_cmbcaridActionPerformed

    private void cmbcaridItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbcaridItemStateChanged
        
    }//GEN-LAST:event_cmbcaridItemStateChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        txtcusid.setText("");
        txtcusname.setText("");
        txtphone.setText("");
        txtrentalfee.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    String custname = txtcusname.getText().toString();
     String phone = txtphone.getText().toString();
    String carmodel = txtcarmodell.getText().toString();
    String carmake =txtcarmake.getText().toString();
    String carid = cmbcarid.getSelectedItem().toString();
    String custid = txtcusid.getText().toString();
//    byte[] image = jlbimg.getIcon();
    
    
    
    String duedate = txtduedate.getText().toString();
    String rentalfee = txtrentalfee.getText().toString();
    String rentalid= txtrentalid.getText().toString();
    String pickdate = txtpickdate.getText().toString();
   
        try {
            String query ="INSERT INTO car_rental(`Car_id`, `Car_make`, `Car_model`, `customer_id`, `Customers_name`, `Phone_no'`, `Pick_date`, `Return_date`, `Rental_Fee`, `Image`, `Rental_id`) VALUES(?,?,?,?,?,?,?,?,?,?,?)";
            con =DriverManager.getConnection("jdbc:mysql://localhost:3306/carhire","root","34852684");
 
           pst1 =con.prepareCall(query);
            pst1.setString(1,carid);
            pst1.setString(2,carmake);
            pst1.setString(3,carmodel);
            pst1.setString(4,custid);
            pst1.setString(5,custname);
            pst1.setString(6,phone);
            pst1.setString(7,pickdate);
            pst1.setString(8,duedate);
            pst1.setString(9,rentalfee);
           pst1.setBytes(10, image);
            pst1.setString(11,rentalid);
            
            pst1.executeUpdate();
                    
               JOptionPane.showMessageDialog(null," CAR ADD ");     
                    
                    
                    } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null," ex");
        }
                    
                   int tax =800; 
                    int vat =467;
                  int  fee =Integer.parseInt(rentalfee);
                    int total;
                   total = tax+vat+fee ;
                    
                    jTextArea1.append("\tVenus Car Rentus  Receipt" +"\n");
                    jTextArea1.append("============================================"+"\n");
                    jTextArea1.append("Car ID:" +"\t\t"+carid +"\n");
                    jTextArea1.append("Car Make :"+"\t\t"+carmake +"\n");
                    jTextArea1.append("Car Model :"+"\t\t"+carmodel +"\n");
                    jTextArea1.append("....................................................................................................." +"\n");
                    jTextArea1.append("Customer ID :"+"\t\t"+custid +"\n");
                    jTextArea1.append("Customers Name :"+"\t\t"+custname +"\n");
                    jTextArea1.append("Phone NO':"+"\t\t"+phone +"\n");
                    jTextArea1.append("......................................................................................................"+"\n");
                    jTextArea1.append("Rental Fee :"+"\t\t"+"=Ksh."+rentalfee +"\n");
                    jTextArea1.append("Pick Date"+"\t\t"+pickdate +"\n");
                    jTextArea1.append("Due Date :"+"\t\t"+duedate +"\n");
                    jTextArea1.append("Rental ID :"+"\t\t"+rentalid +"\n");
                    jTextArea1.append("....................................................................................................." +"\n");
                    jTextArea1.append("\tRental Fee:"+"=Ksh."+rentalfee +"\n");
                    jTextArea1.append("\tTax :"+" = Ksh."+tax +"\n");
                    jTextArea1.append("\tVAT :"+" = Ksh."+vat +"\n");
                    jTextArea1.append("\tTotal"+" = Ksh."+total +"\n");
                    jTextArea1.append("" +"\n");
                    jTextArea1.append("==========="+"welcome venus car rentus"+"============" +"\n");
                    
                    // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        dispose();
        new Home().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtcusidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcusidKeyPressed

        String custid =txtcusid.getText().toString();

        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {

            try {

                con =DriverManager.getConnection("jdbc:mysql://localhost:3306/carhire","root","34852684");
                pst2 =con.prepareStatement("SELECT * FROM `customer` WHERE Customer_id=?");
                pst2.setString(1, custid);
                rs3 = pst2.executeQuery();
                if(rs3.next()==false)
                {
                    JOptionPane.showMessageDialog(this,"customer not available");

                }
                else
                {
                    String username=rs3.getString("User_name");
                    txtcusname.setText(username.trim());

                     String phone=rs3.getString("Phone_no'");
                    txtphone.setText(phone.trim());
                    
                    
                    ;
                    
                    
                    
                    
                    
                }

            }
            // TODO add your handling code here:
            catch (SQLException ex) {
                Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_txtcusidKeyPressed

    private void txtcarmodellKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcarmodellKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcarmodellKeyPressed
private void cmbcaridItemSelected(java.awt.event.ItemEvent evt){

        }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbcarid;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jlbimg;
    private javax.swing.JTextField txtcarmake;
    private javax.swing.JTextField txtcarmodell;
    private javax.swing.JTextField txtcusid;
    private javax.swing.JTextField txtcusname;
    private javax.swing.JTextField txtduedate;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtpickdate;
    private javax.swing.JTextField txtrentalfee;
    private javax.swing.JTextField txtrentalid;
    // End of variables declaration//GEN-END:variables
}
