/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carreg;

import home_page.Home;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class carregistraion extends javax.swing.JFrame {

     Connection con = null;
    PreparedStatement pst =null;
    byte[] photo =null;
    String filename =null;
    PreparedStatement pst1 =null;
    /**
     * Creates new form carregistraion
     */
    public carregistraion() {
        initComponents();
        cmdava.setSelectedItem(-1);
        table_update();
    }
public void table_update()
{
    int c;
    
         try {
             con =DriverManager.getConnection("jdbc:mysql://localhost:3306/carhire","root","34852684");
             pst =con.prepareStatement("SELECT * FROM `vehicle`");
             ResultSet Rs =pst.executeQuery();
             ResultSetMetaData rd = Rs.getMetaData();
             c=rd.getColumnCount();
             DefaultTableModel df =( DefaultTableModel)jTable1.getModel();
             df.setRowCount(0);
             
             while(Rs.next())
             {
         Vector v2 =new Vector();
         for(int i=1;i<=c;i++)
         {
         v2.add(Rs.getString("Car_id"));
         v2.add(Rs.getString("Model"));
        v2.add(Rs.getString("Status"));
        v2.add(Rs.getString("Make"));
         v2.add(Rs.getBytes("Image"));
         }
         
         df.addRow(v2);     
          }
             
         } catch (SQLException ex) {
             Logger.getLogger(carregistraion.class.getName()).log(Level.SEVERE, null, ex);
         }
    
    
    
    
    
    
    



}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcarid = new javax.swing.JTextField();
        txtmodel = new javax.swing.JTextField();
        txtmake = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnadd = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        cmdava = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLimg = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtimg = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnup = new javax.swing.JButton();
        btncancel1 = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(java.awt.Color.cyan);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 50));

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Car_id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Model");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Available");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Make");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        txtcarid.setBackground(new java.awt.Color(102, 255, 204));
        txtcarid.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtcarid.setForeground(new java.awt.Color(0, 0, 0));
        txtcarid.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(txtcarid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 160, 30));

        txtmodel.setBackground(new java.awt.Color(102, 255, 204));
        txtmodel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtmodel.setForeground(new java.awt.Color(0, 0, 0));
        txtmodel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(txtmodel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 160, 30));

        txtmake.setBackground(new java.awt.Color(102, 255, 204));
        txtmake.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtmake.setForeground(new java.awt.Color(0, 0, 0));
        txtmake.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(txtmake, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 160, 30));

        jTable1.setBackground(new java.awt.Color(102, 255, 204));
        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car_id", "Model", "Available", "Make", "Image"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Byte.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 420, 430));

        btnadd.setBackground(new java.awt.Color(128, 221, 234));
        btnadd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnadd.setForeground(new java.awt.Color(0, 0, 0));
        btnadd.setText("Add");
        btnadd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel1.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 70, -1));

        btnedit.setBackground(new java.awt.Color(128, 221, 234));
        btnedit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnedit.setForeground(new java.awt.Color(0, 0, 0));
        btnedit.setText("Edit");
        btnedit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel1.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 70, -1));

        btndel.setBackground(new java.awt.Color(128, 221, 234));
        btndel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btndel.setForeground(new java.awt.Color(0, 0, 0));
        btndel.setText("Delete");
        btndel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });
        jPanel1.add(btndel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 90, -1));

        btncancel.setBackground(new java.awt.Color(128, 221, 234));
        btncancel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btncancel.setForeground(new java.awt.Color(0, 0, 0));
        btncancel.setText("Cancel");
        btncancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel1.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 90, 30));

        cmdava.setBackground(new java.awt.Color(102, 255, 204));
        cmdava.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmdava.setForeground(new java.awt.Color(0, 0, 0));
        cmdava.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        cmdava.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(cmdava, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 160, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 160, 1));

        jPanel5.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 160, 1));

        jPanel4.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 160, 1));

        jLimg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jLimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 320, 200));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Image");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 70, -1));

        txtimg.setBackground(new java.awt.Color(102, 255, 204));
        txtimg.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtimg.setForeground(new java.awt.Color(0, 0, 0));
        txtimg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(txtimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 200, -1));

        jPanel6.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 160, 1));

        btnup.setBackground(new java.awt.Color(51, 204, 255));
        btnup.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnup.setForeground(new java.awt.Color(0, 0, 0));
        btnup.setText("Upload image");
        btnup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupActionPerformed(evt);
            }
        });
        jPanel1.add(btnup, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 160, -1));

        btncancel1.setBackground(new java.awt.Color(128, 221, 234));
        btncancel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btncancel1.setForeground(new java.awt.Color(0, 0, 0));
        btncancel1.setText("Reset");
        btncancel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancel1ActionPerformed(evt);
            }
        });
        jPanel1.add(btncancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 860, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
       
    String car_id = txtcarid.getText();
    String model = txtmodel.getText().toString();
    String status = cmdava.getSelectedItem().toString();
    String make = txtmake.getText().toString();
    
         try {
              String query="INSERT INTO `vehicle`(`car_id`, `Model`, `Status`, `make`,Image) VALUES (?,?,?,?,?)";
             con =DriverManager.getConnection("jdbc:mysql://localhost:3306/carhire","root","34852684");
             
             pst =con.prepareCall(query);
             
             pst.setString(1, car_id);
             pst.setString(2,model);
             pst.setString(3,status );
             pst.setString(4,make );
             pst.setBytes(5, photo);
             pst.executeUpdate();
             
              JOptionPane.showMessageDialog(null," CAR ADD ");
              table_update();
          txtcarid .setText("");
          txtmodel.setText("");
         cmdava.setSelectedIndex(-1);
         txtmake .setText("");
         jLimg.setIcon(new ImageIcon(""));   
             
             
             
             
             
// TODO add your handling code here:
         } catch (SQLException ex) {
             Logger.getLogger(carregistraion.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btnaddActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

      DefaultTableModel d1 =( DefaultTableModel)jTable1.getModel();
      int selectIndex =jTable1.getSelectedRow();
            
      txtcarid.setText(d1.getValueAt(selectIndex,0).toString());
      txtmodel.setText(d1.getValueAt(selectIndex,1).toString());
      cmdava.setSelectedItem(d1.getValueAt(selectIndex,2).toString());
     txtmake.setText(d1.getValueAt(selectIndex,3).toString());
     jLimg.setIcon(new ImageIcon((byte[]) d1.getValueAt(selectIndex,4)));  


        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
      
         try {
             //seting colum carid same as in textfeild carid
             DefaultTableModel d1 =( DefaultTableModel)jTable1.getModel();
             int selectIndex =jTable1.getSelectedRow();
             
             String id=(d1.getValueAt(selectIndex,0).toString());
            String model = txtmodel.getText();
            String status = cmdava.getSelectedItem().toString();
            String make = txtmake.getText();
            
             
             con =DriverManager.getConnection("jdbc:mysql://localhost:3306/carhire","root","34852684");
             pst1=con.prepareStatement("UPDATE `vehicle` SET `Model`=?,`Status`=?,`make`=?,Image = ? WHERE `car_id`=?");
             
             pst1.setString(1,model );
             pst1.setString(2,status);
             pst1.setString(3,make );
             pst1.setBytes(4, photo);
             pst1.setString(5,id );
             pst1.executeUpdate();
             
             JOptionPane.showMessageDialog(null,"RECOND UPDATED");
             table_update();
             
             txtcarid.setText("");
             txtmodel.setText("");
             cmdava.setSelectedItem(-1);
              txtmake.setText("");
             jLimg.setIcon(new ImageIcon(""));
             
             
// TODO add your handling code here:
         } catch (SQLException ex) {
             Logger.getLogger(carregistraion.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btneditActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
     DefaultTableModel d1 =( DefaultTableModel)jTable1.getModel();
             int selectIndex =jTable1.getSelectedRow();
        String id =(d1.getValueAt(selectIndex,0).toString());
        int dialogResult =JOptionPane.showConfirmDialog(this,"Do Want To DELETE The RECOND","Warning",JOptionPane.YES_NO_OPTION
        );
        if(dialogResult ==JOptionPane.YES_OPTION)
        {
        
         try {
             con =DriverManager.getConnection("jdbc:mysql://localhost:3306/carhire","root","34852684");
             pst=con.prepareStatement("DELETE FROM `vehicle`  WHERE `car_id`=?");
             
             pst.setString(1,id );
             pst.executeUpdate();
              JOptionPane.showMessageDialog(null,"RECOND DELETED");
             table_update();
             
              txtcarid.setText("");
             txtmodel.setText("");
             cmdava.setSelectedItem(-1);
              txtmake.setText("");
             jLimg.setIcon(new ImageIcon(""));
// TODO add your handling code here:
         } catch (SQLException ex) {
             Logger.getLogger(carregistraion.class.getName()).log(Level.SEVERE, null, ex);
         }
        }
        else
        {
        
        
        
        }
    }//GEN-LAST:event_btndelActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
  
dispose();
 new Home().setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupActionPerformed
JFileChooser chooser = new JFileChooser();
chooser.showOpenDialog(null);
File f =chooser.getSelectedFile();
jLimg.setIcon(new ImageIcon(f.toString()));
filename =f.getAbsolutePath();
txtimg.setText(filename);

   try{
       File image =new File(filename);
       FileInputStream fi =new FileInputStream(image);
       ByteArrayOutputStream bu =new ByteArrayOutputStream();
       byte[] buf =new byte[1024];
        
       for(int readNum; (readNum = fi.read(buf))!=-1;)
       {
         bu.write(buf,0, readNum);
         
       }
       photo =bu.toByteArray();
       
       
       
   } catch (Exception ex) {
             Logger.getLogger(carregistraion.class.getName()).log(Level.SEVERE, null, ex);
         }




        // TODO add your handling code here:
    }//GEN-LAST:event_btnupActionPerformed

    private void btncancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancel1ActionPerformed
             txtcarid.setText("");
             txtmodel.setText("");
             cmdava.setSelectedItem(-1);
              txtmake.setText("");
             jLimg.setIcon(new ImageIcon(""));





        // TODO add your handling code here:
    }//GEN-LAST:event_btncancel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(carregistraion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(carregistraion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(carregistraion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(carregistraion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new carregistraion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btncancel1;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnup;
    private javax.swing.JComboBox<String> cmdava;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLimg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtcarid;
    private javax.swing.JTextField txtimg;
    private javax.swing.JTextField txtmake;
    private javax.swing.JTextField txtmodel;
    // End of variables declaration//GEN-END:variables
}
