/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import reg.registration;

/**
 *
 * @author Admin
 */
public class login extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst =null;
    

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }
public void welcome()
{
     String username = txtusername.getText();
txtwecome.setText(username + "welcome to venus car renters" );


}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtconpass = new javax.swing.JPasswordField();
        txtpass = new javax.swing.JPasswordField();
        txtname = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        btnregister = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtidno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        txtwecome = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(728, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("OptionPane.questionDialog.titlePane.foreground"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.window);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("registration");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 280, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 40));

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Password * :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("phone no' :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Email * :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Name * :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, 20));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Conferm Password :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("User Name * :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        txtconpass.setBackground(new java.awt.Color(133, 192, 226));
        txtconpass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(txtconpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 250, 20));

        txtpass.setBackground(new java.awt.Color(133, 192, 226));
        txtpass.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtpass.setForeground(new java.awt.Color(0, 0, 0));
        txtpass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 250, -1));

        txtname.setBackground(new java.awt.Color(133, 192, 226));
        txtname.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(0, 0, 0));
        txtname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 250, -1));

        txtphone.setBackground(new java.awt.Color(133, 192, 226));
        txtphone.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtphone.setForeground(new java.awt.Color(0, 0, 0));
        txtphone.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 250, -1));

        txtemail.setBackground(new java.awt.Color(133, 192, 226));
        txtemail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtemail.setForeground(new java.awt.Color(0, 0, 0));
        txtemail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 250, -1));

        txtusername.setBackground(new java.awt.Color(133, 192, 226));
        txtusername.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtusername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        jPanel2.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 250, -1));

        btnregister.setBackground(new java.awt.Color(0, 255, 255));
        btnregister.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnregister.setForeground(new java.awt.Color(0, 0, 0));
        btnregister.setText("Register");
        btnregister.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });
        jPanel2.add(btnregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 110, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("ID NO' * :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        txtidno.setBackground(new java.awt.Color(133, 192, 226));
        txtidno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtidno.setForeground(new java.awt.Color(0, 0, 0));
        txtidno.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(txtidno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 250, 20));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Provide  you user information feilds marked with * are  mandatory.");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 470, -1));

        jPanel3.setBackground(java.awt.Color.red);
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 250, 2));

        jPanel5.setBackground(java.awt.Color.red);
        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 250, 2));

        jPanel6.setBackground(java.awt.Color.red);
        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 250, 2));

        jPanel7.setBackground(java.awt.Color.red);
        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 250, 2));

        jPanel8.setBackground(java.awt.Color.red);
        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 250, 2));

        jPanel4.setBackground(java.awt.Color.red);
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 250, 2));

        jPanel10.setBackground(java.awt.Color.red);
        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 250, 2));
        jPanel2.add(txtwecome, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 9, 360, 30));

        jButton1.setBackground(new java.awt.Color(102, 255, 204));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Login");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 80, -1));

        jLabel4.setBackground(java.awt.Color.red);
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/11.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 728, 450));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 740, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
       
    String name = txtname.getText();
    String password = txtpass.getText().toString();
    String username = txtusername.getText();
    String phoneno = txtphone.getText().toString();
    String email = txtidno.getText();
    String idno = txtemail.getText().toString();
        if(name.isEmpty()||password.isEmpty()||username.isEmpty()||phoneno.isEmpty()||email.isEmpty()||idno.isEmpty()){
        JOptionPane.showMessageDialog(this," None of the feild can be emty","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
        try{
    String query ="INSERT INTO `customer`(`Customer_id`, `Name`, `User_name`, `Phone_no'`, `Email`, `Password`) VALUES (?,?,?,?,?,?)" ;
    con =DriverManager.getConnection("jdbc:mysql://localhost:3306/carhire","root","34852684");
    pst =con.prepareCall(query);
    pst.setString(1, idno);
    pst.setString(2, name);
    pst.setString(3, username);
    pst.setString(4, phoneno);
    pst.setString(5, email);
    pst.setString(6, password);
    pst.executeUpdate();
    JOptionPane.showMessageDialog(null,"REGISTER SUCCESSFULLY");
     txtname.setText("");
     txtpass.setText("");
     txtusername.setText("");
     txtphone.setText("");    
     txtidno.setText("");
     txtemail.setText("");
}catch(Exception ex){
     JOptionPane.showMessageDialog(null,"x");
}}


    }//GEN-LAST:event_btnregisterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     dispose();
      new registration().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregister;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField txtconpass;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtidno;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtusername;
    private javax.swing.JTextField txtwecome;
    // End of variables declaration//GEN-END:variables

   
   
}
