/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package retuncar;

import home_page.Home;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Return_cr extends javax.swing.JFrame {
Connection con = null;
 PreparedStatement pst1 =null;
    PreparedStatement pst =null;
    ResultSet rs1 =null;
    
    ResultSet rs =null;
    byte[] photo =null;
    String carid = null;
    String carmodel = null;
    String carmake = null;
    String custid = null;
    String pay = null;
    String custname= null;
    String rentalid = null;
    String pickdate = null;
    String duedate = null;
    String phone = null;
    
    
    
    
    public Return_cr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        txtcusid = new javax.swing.JTextField();
        txtcusname = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlbimg = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        txtduedate = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtrentalid = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtcarmake = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        txtcarmodell = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcarid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cmbpaid = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(java.awt.Color.white);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Customer id :");
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Custoner name:");
        jLabel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 88, 28));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Back");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 70, -1));

        jButton5.setBackground(new java.awt.Color(0, 88, 28));
        jButton5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Rent");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 70, 30));

        jButton6.setBackground(new java.awt.Color(0, 88, 28));
        jButton6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("Cancle");
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, 80, -1));

        txtcusid.setBackground(java.awt.Color.white);
        txtcusid.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtcusid.setForeground(new java.awt.Color(0, 0, 0));
        txtcusid.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtcusid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcusidKeyPressed(evt);
            }
        });
        jPanel6.add(txtcusid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 180, 20));

        txtcusname.setBackground(java.awt.Color.white);
        txtcusname.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtcusname.setForeground(new java.awt.Color(0, 0, 0));
        txtcusname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(txtcusname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 180, 20));

        jPanel7.setBackground(new java.awt.Color(0, 255, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 180, 1));

        jPanel8.setBackground(new java.awt.Color(0, 255, 51));
        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 180, 1));

        jPanel9.setBackground(new java.awt.Color(0, 255, 51));
        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 180, 1));

        jPanel4.setBackground(new java.awt.Color(0, 255, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 180, 1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("paid");
        jLabel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Car id :");
        jLabel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jlbimg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 102), new java.awt.Color(102, 255, 102), new java.awt.Color(102, 255, 102), new java.awt.Color(102, 255, 153)));
        jPanel6.add(jlbimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 300, 200));

        jButton7.setBackground(new java.awt.Color(0, 88, 28));
        jButton7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("print");
        jButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, 70, -1));

        txtduedate.setBackground(java.awt.Color.white);
        txtduedate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtduedate.setForeground(new java.awt.Color(0, 0, 0));
        txtduedate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(txtduedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 180, 20));

        jPanel11.setBackground(new java.awt.Color(0, 255, 51));
        jPanel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 180, 1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Due date :");
        jLabel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jPanel12.setBackground(new java.awt.Color(0, 255, 51));
        jPanel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 180, 1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Pick date :");
        jLabel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Image");
        jLabel14.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jPanel14.setBackground(new java.awt.Color(0, 255, 51));
        jPanel14.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 180, 1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Rental id  :");
        jLabel15.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        txtrentalid.setBackground(java.awt.Color.white);
        txtrentalid.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtrentalid.setForeground(new java.awt.Color(0, 0, 0));
        txtrentalid.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtrentalid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrentalidActionPerformed(evt);
            }
        });
        txtrentalid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtrentalidKeyPressed(evt);
            }
        });
        jPanel6.add(txtrentalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 180, 20));

        jPanel13.setBackground(new java.awt.Color(0, 255, 51));
        jPanel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 180, 1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Car Make :");
        jLabel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txtcarmake.setBackground(java.awt.Color.white);
        txtcarmake.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtcarmake.setForeground(new java.awt.Color(0, 0, 0));
        txtcarmake.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtcarmake.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcarmakeKeyPressed(evt);
            }
        });
        jPanel6.add(txtcarmake, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 180, 20));

        jPanel15.setBackground(new java.awt.Color(0, 255, 51));
        jPanel15.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 180, 1));

        txtcarmodell.setBackground(java.awt.Color.white);
        txtcarmodell.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtcarmodell.setForeground(new java.awt.Color(0, 0, 0));
        txtcarmodell.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtcarmodell.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcarmodellKeyPressed(evt);
            }
        });
        jPanel6.add(txtcarmodell, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 180, 20));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Car Model:");
        jLabel16.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Please  Enter you Customer Id Below To Rent Car");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 360, 20));

        txtcarid.setBackground(java.awt.Color.white);
        txtcarid.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtcarid.setForeground(new java.awt.Color(0, 0, 0));
        txtcarid.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtcarid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcaridActionPerformed(evt);
            }
        });
        jPanel6.add(txtcarid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 180, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rental_id", "Car_id", "car_model", "Car_make", "Customer_id", "Customer_name", "Phone_no", "Pick_date", "Retun)_date", "Image", "Paid"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 560, 90));

        cmbpaid.setBackground(new java.awt.Color(153, 255, 153));
        cmbpaid.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmbpaid.setForeground(new java.awt.Color(0, 0, 0));
        cmbpaid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        cmbpaid.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cmbpaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbpaidActionPerformed(evt);
            }
        });
        jPanel6.add(cmbpaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 180, -1));
        jPanel6.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 140, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 940, 740));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 960, 640));

        jPanel1.setBackground(new java.awt.Color(51, 27, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("RETURN  CAR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 12, 160, 28));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        dispose();
        new Home().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

       

        try {
            String query ="INSERT INTO retun_car(`Car_id`, `Car_make`, `Car_model`, `customer_id`, `Customers_name`, `Phone_no'`, `Pick_date`, `Return_date`, `Rental_Fee`, `Rental_id`) VALUES(?,?,?,?,?,?,?,?,?,?)";
            con =DriverManager.getConnection("jdbc:mysql://localhost:3306/carhire","root","34852684");

            pst1 =con.prepareCall(query);
            pst1.setString(1,carid);
            pst1.setString(2,carmake);
            pst1.setString(3,carmodel);
            pst1.setString(4,custid);
            pst1.setString(5,custname);
            pst1.setString(6,phone);
            pst1.setString(7,pickdate);
            pst1.setString(8,duedate);
            pst1.setString(9,pay);
            //           pst1.setBytes(10, image);
            pst1.setString(10,rentalid);

            pst1.executeUpdate();

            JOptionPane.showMessageDialog(null," CAR ADD ");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null," ex");
        }


        // TODO add your handling code here:

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        txtcusid.setText("");
        txtcusname.setText("");
        cmbpaid.setSelectedItem("-1");
        txtcarmake.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtcarmakeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcarmakeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcarmakeKeyPressed

    private void txtcarmodellKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcarmodellKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcarmodellKeyPressed

    private void txtrentalidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrentalidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrentalidActionPerformed

    private void txtrentalidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrentalidKeyPressed
       String rentalid =txtrentalid.getText().toString();

        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {

            try {

                con =DriverManager.getConnection("jdbc:mysql://localhost:3306/carhire","root","34852684");
                pst =con.prepareStatement("SELECT * FROM `car_rental` WHERE Rental_id=?");
                pst.setString(1, rentalid );
                rs1 = pst.executeQuery();
                if(rs1.next()==false)
                {
                    JOptionPane.showMessageDialog(this,"customer not available");

                }
                else
                {
                    String username=rs1.getString("Customers_name");
                    txtcusname.setText(username.trim());

//                    String paid=rs1.getString("Paid");
//                    cmbpaid.setSelectedItem(paid.trim());
                   
                    String carmake=rs1.getString("Car_make");
                    txtcarmake.setText(carmake.trim());
                    
                    String carmodel=rs1.getString("Car_model");
                    txtcarmodell.setText(carmodel.trim());
                    
                    String custid=rs1.getString("customer_id");
                    txtcusid.setText(custid.trim());
                    
//                    String pickdate=rs1.getString("Pick_date");
//                    txtpickdate.setText(pickdate.trim());
//                    
                    String duedate=rs1.getString("Return_date");
                    txtduedate.setText(duedate.trim());
                    
                    byte[] image =rs1.getBytes("Image");
                    jlbimg.setIcon(new ImageIcon(image));
                    
                   
                    String carid=rs1.getString("Car_id");
                    txtcarid.setText(carid.trim());
                    
                   
                    
                    
                    

                }

            }
            // TODO add your handling code here:
            catch (SQLException ex) {
                Logger.getLogger(Return_cr.class.getName()).log(Level.SEVERE, null, ex);
            }

        }











        // TODO add your handling code here:
    }//GEN-LAST:event_txtrentalidKeyPressed

    private void txtcaridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcaridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcaridActionPerformed

    private void cmbpaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbpaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbpaidActionPerformed

    private void txtcusidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcusidKeyPressed

    }//GEN-LAST:event_txtcusidKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Return_cr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Return_cr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Return_cr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Return_cr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return_cr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbpaid;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlbimg;
    private javax.swing.JTextField txtcarid;
    private javax.swing.JTextField txtcarmake;
    private javax.swing.JTextField txtcarmodell;
    private javax.swing.JTextField txtcusid;
    private javax.swing.JTextField txtcusname;
    private javax.swing.JTextField txtduedate;
    private javax.swing.JTextField txtrentalid;
    // End of variables declaration//GEN-END:variables
}
